### ISSUE TITLE
Insertion sort sorts biggest to smallest

### ISSUE THREAD

**Issue by cmcqueen** [p1v0t/Sort#4]
I tried the insertion sort, and found that it sorts biggest to smallest, the opposite of C standard library `qsort()` (with my provided element sort function).

It would be good to make all the algorithms consistent with the C standard `qsort()` behaviour in that regard.

**Comment by p1v0t** [comment]
Fixed!!! 
Kind apologies for the late feedback. Now I need to fix the API of `qsortL` and `qsortH` to eleminate 1 more argument to make it look like std `qsort`. But insertion sort and other basic sorting algorithms now sorting smallest to biggest.
